spring:
  cache:
    type: none
  main:
    lazy-initialization: true
  jpa:
    properties:
      org.hibernate.flushMode: ALWAYS
wait:
  explicit:
    seconds: 60
  implicit:
    seconds: 50
report:
  baseDir: target/reports
  allure: ${report.baseDir}/allure-report
  extent:
    dir: ${report.baseDir}/extent
    file: ${report.extent.dir}/ExtentReport.html
  screenshots: ${report.baseDir}/screenshots
webDriver:
  mode: browserStack
  browser: Chrome
  browserStack:
    local: true
    os: OS X
    osVersion: Big Sur
    browserVersion: latest
    browserName: Safari
    domain: hub-cloud.browserstack.com/wd/hub
    username: konstantinasfalk_nRhdcJ
    key: hKWrodwfpD9scNcnWBaX
url:
  ui-url: https://shop.stage.klix.app/demo