name: Java CI with Maven

#on: [ push ]

on:
#  schedule:
#    - cron: '00 18 * * *'
  push:
    branches: [ main ]
    pull_request:
      branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        if: always()
        run: mvn clean test -Dsurefire.suiteXmlFiles=./src/test/resources/suites/frontend/e2e.xml -Dspring.profiles.active=stage
        continue-on-error: true

      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: target/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
#        env:
        with:
# PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          deploy_key: ${{ secrets.deploy_key_win }}
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          repo-token: ${{ secrets.GITHUB_TOKEN }}
#          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: gh-pages
          publish_dir: allure-history
